@startuml

class ATmega_One_Wire_Interaction_Layer <<Component_Type>>
{
  This Component_Type allows to manage a 1-Wire bus through a
  digital pin of an ATmega chip.
  --
  +Pin_Address:uint8
  +Bit_Index:uint8
}

@enduml
