@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

!includeurl https://raw.githubusercontent.com/HomeMadeBots/ATmega_One_Wire/main/doc/ATmega_One_Wire.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/One_Wire_Interfaces/main/doc/One_Wire_Interfaces.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Bits_Management/main/doc/Bits_Management.puml
!includeurl https://raw.githubusercontent.com/HomeMadeBots/Embedded_C_Framework/main/doc/Embedded_C_Framework.puml

ATmega_One_Wire ..> One_Wire_Interfaces
note on link : realized interface

ATmega_One_Wire ..> Bits_Management
note on link : for internal design

ATmega_One_Wire ..> Embedded_C_Framework
note on link : for internal design

Bits_Management ..> Embedded_C_Framework
@enduml